### PR TITLE
Merge into master

### PR DESCRIPTION
**Pull request by Abazzi**

### CODE REVIEW

**Comment by mgellakkis** [comment]
Which class the presentation is in 55?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Abazzi** [comment]
The presentations were this morning

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mgellakkis** [comment]
What, I thought it was in class time!!!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Abazzi** [comment]
Cai told us that it would be when we usually have iOS yesterday

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mgellakkis** [comment]
Sorry I missed it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
